FROM python:3.9-slim-buster
WORKDIR /app
COPY . /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    libc-dev \
    libffi-dev \
    libssl-dev \
    python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
#RUN pip install scikit-learn==1.5.0
RUN apt-get update && pip install -r requirements.txt
CMD ["python", "main.py"]