version: "3"
services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    image: airflowimage
    container_name: price_prediction_airflow
    ports:
      - "8080:8080"

  flaskapp:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: flaskimage
    container_name: price_prediction_flask
    ports:
      - "80:80"