stages:
  training:
    cmd: python src/pipeline/test_pipeline.py

    deps:
      - src/pipeline/test_pipeline.py
      - src/components/data_cleaning.py
      - src/components/data_ingestion.py
      - src/components/data_transformation.py
      - src/components/model_trainer.py
    
    outs:
      - artifacts/model.pkl
      - artifacts/preprocessor.pkl